MS-20: Interviews - Update interview
damianalvarez/BaSD-MindSet pull request #11
Opened 2021-11-06 05:55 UTC by NicoMunoz909

2021-11-06 17:16 UTC, damianalvarez requested changes

2021-11-06 17:16 UTC, damianalvarez commented on index.js
> +  let interview = interviewsController.create(req.query);
@NicoMunoz909 In the routes declaration, let's keep the controller method calls as the examples below (e.g Admin)

`app.get('/interviews/create', interviewsController.create)`

2021-11-06 17:16 UTC, damianalvarez commented on index.js
> +const interviewsController = require('./controllers/interviews');
@NicoMunoz909 let's move this line above the line 5

2021-11-06 17:16 UTC, damianalvarez commented on data/interviews.json
> +[{"id":1,"idCandidate":"223","idClient":"60","idPosition":"20","date":"11/22/2021","time":"22:08","status":"Finished"},{"id":"2","idCandidate":"234","idClient":"9876","idPosition":"75","date":"27/11/
@NicoMunoz909 can you please format this mock using this tool? https://format-express.dev/ Just to make it more readable

2021-11-06 17:16 UTC, damianalvarez commented on controllers/interviews.js
> +    const data = JSON.parse(fs.readFileSync('./data/interviews.json'));
@NicoMunoz909 Let's move this line outside this method, I think that below the first line is a good place for this const.

2021-11-06 17:16 UTC, damianalvarez commented on controllers/interviews.js
> +    let interview = {
@NicoMunoz909 this could be a const instead

2021-11-06 17:16 UTC, damianalvarez commented on controllers/interviews.js
> +    fs.writeFile('./data/interviews.json', JSON.stringify(data), err => {
@NicoMunoz909 let's avoid writing the changes on the json mocks.

2021-11-06 17:16 UTC, damianalvarez commented on controllers/interviews.js
> +    fs.writeFile('./data/interviews.json', JSON.stringify(data), err => {
@NicoMunoz909 same here

2021-11-06 17:16 UTC, damianalvarez commented on controllers/interviews.js
> +    })
@NicoMunoz909 some semicolons are missing starting here

2021-11-06 17:16 UTC, damianalvarez commented on controllers/interviews.js
> +    if(index === -1) return 'Could not find interview with specified ID'
@NicoMunoz909 We need to give responses to the clients that are consuming the backend resources, so let's use `res.send('');` in order to generate responses to the clients

2021-11-07 02:35 UTC, nicolasblasco commented on data/interviews.json
> +[{"id":1,"idCandidate":"223","idClient":"60","idPosition":"20","date":"11/22/2021","time":"22:08","status":"Finished"},{"id":"2","idCandidate":"234","idClient":"9876","idPosition":"75","date":"27/11/
@NicoMunoz909 watch out for the id type. In your mock data, some ids are string and some are numbers. The id must be a string.

2021-11-07 17:03 UTC, NicoMunoz909 commented on controllers/interviews.js
> +    const data = JSON.parse(fs.readFileSync('./data/interviews.json'));
@damianalvarez I put it there because otherwise it would only parse the data once and when the data gets changed in one call, succesive calls will use outdated data

2021-11-07 17:53 UTC, closed without merging

2021-11-07 17:58 UTC, NicoMunoz909 commented
I deleted this PR as I changed the branch name