MS-28 - Sessions - Update Session
damianalvarez/BaSD-MindSet pull request #13
Opened 2021-11-06 19:25 UTC by nicolasblasco

Task:
- update a session 

Commit history :
- Add endpoint to update session
-  Add function to update session
- Add if stament to return message when id can't be changind in update function
- Add message when id not found in update function
- Add message when id not found in update function
- Add update to module exports
- Fix code identation

2021-11-06 23:15 UTC, BaltazarCortina commented on controllers/sessions.js
> +            id: req.query.id,
You're already sending the id as a param, there's no need to send it again as a query param.

2021-11-07 02:13 UTC, nicolasblasco commented on controllers/sessions.js
> +            id: req.query.id,
I send it because if someone wants to change the id of the session, the if statment below shows a message that you can't change the id. It's true that if you erase line 21 (id: req.query.id), then you can't modify the id and that would solve the problem of someone wanting to change the id. 
Should we consider not showing any messages if someone wants to modify the id or just directly no let some to be able to modify it, meaning I would erase line 21 & if statment

2021-11-07 13:16 UTC, EugenioPonzone commented on controllers/sessions.js
> +            id: req.query.id,
Nico, you can take a look on my new PR and balti's. You'll be able to simplify 19-27  lines in only one.
Ex:  **const updateSession = req.query;**
session.idPsychologist = updateSession.idPsychologist ? updateSession.idPsychologist : session.idPsychologist;
...
That's works in the same way. I think that's balti wanted to say.

2021-11-07 13:39 UTC, damianalvarez requested changes

2021-11-07 13:39 UTC, damianalvarez commented on controllers/sessions.js
> +            id: req.query.id,
Hey @nicolasblasco, given that the IDs will be managed by the database engine in the future let's get rid of this line and the validation on line 28 as well. The API should not give clients the ability to change database IDs since it is a very dangerous operation.

2021-11-07 13:39 UTC, damianalvarez commented on controllers/sessions.js
> +        session.result = updateSession.result ? updateSession.result : session.result;
@nicolasblasco we need to save the change on the object of the sessions' array.

2021-11-07 15:00 UTC, damianalvarez approved these changes

2021-11-07 15:00 UTC, merged