MS-15: Profiles - Create Profile (2)
damianalvarez/BaSD-MindSet pull request #15
Opened 2021-11-06 20:26 UTC by luisnannini

Fix PR corrections and merge with latest Develop

2021-11-06 23:06 UTC, BaltazarCortina submitted a review, later dismissed

2021-11-06 23:06 UTC, BaltazarCortina commented on controllers/profiles.js
> +        id: req.query.id,
Id should be assigned by the server when you create a new profile, it's should not be send as part of the request.

2021-11-07 02:37 UTC, nicolasblasco commented on data/profiles.json
> +    "id": 1,
@luisnannini id type must be a string. This change must be for all the objects of the mock data.

2021-11-07 13:25 UTC, damianalvarez requested changes

2021-11-07 13:25 UTC, damianalvarez commented on controllers/profiles.js
> +        id: req.query.id,
@luisnannini as @BaltazarCortina said, the IDs will be set automatically by the database engine, so let's get rid of line 12. We can assign the ID's counting the number of profiles that are on the array and then adding one to that number

```id: profiles.length + 1```

2021-11-07 20:37 UTC, damianalvarez approved these changes

2021-11-07 20:37 UTC, merged