MS-03: create candidates
damianalvarez/BaSD-MindSet pull request #16
Opened 2021-11-06 20:30 UTC by ValentinaCollareta

- Add candidates.js
- Add candidates.json
- Add functions to create new candidates
- Integrate functions from MS-06: get all candidates, get candidates by Id and get candidates by Name

2021-11-06 23:03 UTC, BaltazarCortina requested changes

2021-11-06 23:03 UTC, BaltazarCortina commented on controllers/candidates.js
> +        profiles: req.query.profiles,
Profiles should be empty until the session with the psychologist, it shouldn't be part of the request either.

2021-11-07 13:27 UTC, damianalvarez requested changes

2021-11-07 13:27 UTC, damianalvarez commented on controllers/candidates.js
> +        profiles: req.query.profiles,
@BaltazarCortina good catch

2021-11-07 13:28 UTC, damianalvarez requested changes
@ValentinaCollareta Let's solve the comments that @BaltazarCortina mentioned along the PR and merge this one 🌈

2021-11-07 20:18 UTC, damianalvarez approved these changes

2021-11-07 20:20 UTC, merged