MS-11: Clients -List Clients
damianalvarez/BaSD-MindSet pull request #17
Opened 2021-11-06 21:23 UTC by amacazzaga

Task : Created List of Clients
Commit history:  inicial commit

@amacazzaga
amacazzaga committed yesterday
 
Commits on Nov 6, 2021
MS-11 list client working properly

2021-11-06 21:28 UTC, nicolasblasco commented on controllers/clients.js
> +  const getByphoneNumber = (req, res) => {
Spaces between each function

2021-11-06 21:30 UTC, nicolasblasco commented on controllers/clients.js
> +
Fix space indentation

2021-11-06 21:31 UTC, nicolasblasco commented on data/clients.json
> +    "id": 1,
Change id type to string

2021-11-06 21:36 UTC, amacazzaga commented on controllers/clients.js
> +
fix!

2021-11-06 21:52 UTC, nicolasblasco commented on controllers/clients.js
> +  const client = clients.find((client) => client.id == req.params.id);
Use ===

2021-11-06 22:56 UTC, BaltazarCortina requested changes

2021-11-06 22:56 UTC, BaltazarCortina commented on controllers/clients.js
> +  getByphoneNumber: getByphoneNumber,
The p en phone should be uppercase: getByPhoneNumber

2021-11-06 22:56 UTC, BaltazarCortina commented on controllers/clients.js
> +const getByphoneNumber = (req, res) => {
The p en phone should be uppercase: getByPhoneNumber

2021-11-06 22:56 UTC, BaltazarCortina commented on index.js
> +app.get('/clients/byphoneNumber/:phoneNumber', clientsController.getByphoneNumber);
Same in the route: byPhoneNumber

2021-11-07 13:36 UTC, damianalvarez requested changes
@amacazzaga the PR looks good, let's solve the comments that @BaltazarCortina left and merge this one

2021-11-07 20:31 UTC, damianalvarez approved these changes

2021-11-07 21:03 UTC, merged