MS-01: Admin - Update admin
damianalvarez/BaSD-MindSet pull request #18
Opened 2021-11-06 22:44 UTC by BaltazarCortina

Create endpoint and function to update admin.

2021-11-07 13:41 UTC, damianalvarez requested changes

2021-11-07 13:41 UTC, damianalvarez commented on controllers/admins.js
> +const update = (req, res) => {
@BaltazarCortina I think we can simplify this logic using a find operator as @nicolasblasco did in this PR https://github.com/damianalvarez/BaSD-MindSet/pull/13/files

2021-11-07 13:41 UTC, damianalvarez commented on controllers/admins.js
> +      }
@BaltazarCortina keep in mind that we need to save the change on the admins' array

2021-11-07 22:54 UTC, BaltazarCortina commented on controllers/admins.js
> +      }
Aren't we already doing that by looping through the array and changing the element's properties?

2021-11-07 22:58 UTC, BaltazarCortina commented on controllers/admins.js
> +const update = (req, res) => {
I did it this way because it solved the issue of having to replace the element in the array, but I can change it if it's better that way.

2021-11-08 01:10 UTC, damianalvarez approved these changes

2021-11-08 01:10 UTC, merged