MS-07 Psychologists - Create Psychologists
damianalvarez/BaSD-MindSet pull request #19
Opened 2021-11-06 22:56 UTC by JamirMansilla

##Commits:

- MS-07: fill json with random data
- MS-07: add psychologist functions in psychologist.js
- MS-07: add endpoint to index.js

2021-11-07 02:27 UTC, nicolasblasco commented on data/psychologists.json
> +    },
@JamirMansilla fix identation of mock data of psychologist with id: 3

2021-11-07 02:28 UTC, nicolasblasco commented on data/psychologists.json
> +        "id":1,
@JamirMansilla change id type to string. Do this for all objects of the mock data.

2021-11-07 02:30 UTC, nicolasblasco commented on data/psychologists.json
> +        "enrollmentNumber":6603,
@JamirMansilla change enrollmentNumber type to string. Do this for all objects of the mock data. 
To see which data type goes for each property, see the excel "Recursos"

2021-11-07 13:42 UTC, damianalvarez requested changes
@JamirMansilla let's solve the comments that @nicolasblasco left before merging this one

2021-11-07 20:30 UTC, damianalvarez requested changes

2021-11-07 20:30 UTC, damianalvarez commented on controllers/psychologists.js
> +        id: req.query.id,
@JamirMansilla let's get rid of this property, the ID will be auto-assigned by the DB engine

2021-11-07 23:18 UTC, BaltazarCortina requested changes

2021-11-07 23:18 UTC, BaltazarCortina commented on controllers/psychologists.js
> +        name: req.query.name,
@JamirMansilla we should also assign an id to every new psychologist.

2021-11-07 23:18 UTC, BaltazarCortina commented on index.js
> +});
@JamirMansilla These lines are already at the end, they shouldn't be repeated here.

2021-11-07 23:18 UTC, BaltazarCortina commented on index.js
> +
@JamirMansilla can we get rid of the empty space in the last line?

2021-11-08 00:44 UTC, BaltazarCortina approved these changes

2021-11-08 00:44 UTC, damianalvarez approved these changes

2021-11-08 00:45 UTC, merged