MS-22: Interviews - List interviews
damianalvarez/BaSD-MindSet pull request #22
Opened 2021-11-07 17:56 UTC by NicoMunoz909

Implemented 4 features:
- MS-19: Interviews - Create Interview
- MS-20: Interviews - Update Interviews
- MS-21: Interviews - Cancel Interview
- MS-22: Interviews - List Interviews

2021-11-07 20:28 UTC, damianalvarez requested changes

2021-11-07 20:28 UTC, damianalvarez commented on controllers/interviews.js
> +const cancel = (req, res) => {
@NicoMunoz909 let's rename this method as `remove`

2021-11-07 21:27 UTC, EugenioPonzone commented on controllers/interviews.js
> +        return req.params.id === interview.id;
Muña,  you could take advantage of the arrow function and simplify in only one line without the return. 
Take a look on every case that you've implemented  arrow functions in that way.

2021-11-07 23:29 UTC, BaltazarCortina requested changes

2021-11-07 23:29 UTC, BaltazarCortina commented on controllers/interviews.js
> +        id: `${Math.round(Math.random()*10000)}`,
@NicoMunoz909 this way of creating ids can lead to repeated ids, we could solve this by checking that the new id doesn't already exist.

2021-11-08 04:31 UTC, NicoMunoz909 commented on controllers/interviews.js
> +        id: `${Math.round(Math.random()*10000)}`,
Didn't think about that. Fixed it using a do-while loop. Thanks!

2021-11-08 11:08 UTC, damianalvarez approved these changes

2021-11-08 11:08 UTC, merged