MS-05: remove candidates
damianalvarez/BaSD-MindSet pull request #23
Opened 2021-11-07 20:12 UTC by ValentinaCollareta

- Add candidates.js
- Add candidates.json
- Add function to remove candidates by Id

2021-11-07 20:24 UTC, damianalvarez requested changes

2021-11-07 20:24 UTC, damianalvarez commented on controllers/candidates.js
> +    candidates[index] = {};
@ValentinaCollareta in this case you are assigning an empty object to that position instead of removing the item. Did you try filtering all the candidates and returning all the items but the one with the same id that has been passed as a param?

2021-11-07 23:34 UTC, BaltazarCortina requested changes

2021-11-07 23:34 UTC, BaltazarCortina commented on controllers/candidates.js
> +      name: req.query.name,
@ValentinaCollareta we should also assign an id to every new candidate.

2021-11-08 00:15 UTC, BaltazarCortina requested changes

2021-11-08 00:15 UTC, BaltazarCortina commented on controllers/candidates.js
> +    id: index + 1,
@ValentinaCollareta id should be a string, and index + 1 returns a number, we should parse it to string before assigning it.

2021-11-08 01:19 UTC, EugenioPonzone commented on controllers/candidates.js
> +    id: index + 1,
What happen if you have for example 5 candidates (id 1 2 3 4 5) , then you remove one (for instance the id=2) and then create another one? The candidates.length=4 and the new candidate ID will be 5 (repeated), won't it?

2021-11-08 01:21 UTC, EugenioPonzone commented on controllers/candidates.js
> +    id: index + 1,
I believe that we could try " id :  candidates[ candidates.length -1].id + 1 "

2021-11-08 13:12 UTC, BaltazarCortina approved these changes

2021-11-08 16:07 UTC, damianalvarez approved these changes

2021-11-08 16:07 UTC, merged