Feature/ms 13/remove client
damianalvarez/BaSD-MindSet pull request #31
Opened 2021-11-08 03:23 UTC by amacazzaga

Just  a few lines of code to remove clients (from 71, to 80)

2021-11-08 03:38 UTC, nicolasblasco commented
@amacazzaga remember to add Damian as a reviewer

2021-11-08 03:38 UTC, luisnannini commented
CAREFUL ! you are trying to merge into Main instead of Develop. Also please add a Reviewer and rename the PR title correctly.

2021-11-08 11:20 UTC, damianalvarez requested changes
@amacazzaga can you please, point this branch to `develop` and give some format to the PR title?

2021-11-08 16:09 UTC, damianalvarez requested changes

2021-11-08 16:09 UTC, damianalvarez commented on controllers/clients.js
> +    const clientRemoved = clientsFilter;
@amacazzaga I think you need to assign the filtered clients to the original clients array here. And return only the cleints filtered array on the line 78

2021-11-08 21:11 UTC, damianalvarez requested changes

2021-11-08 21:11 UTC, damianalvarez commented on controllers/clients.js
> +    const clientsFilter = clients.filter((client) => client.id !== req.params.id);
@amacazzaga can we rename this constant to `filteredClients`?

2021-11-08 21:11 UTC, damianalvarez commented on controllers/clients.js
> +    res.json({client,clients});
@amacazzaga, can we only return the removed client in the response?

2021-11-08 23:57 UTC, damianalvarez approved these changes

2021-11-09 03:12 UTC, damianalvarez requested changes

2021-11-09 03:12 UTC, damianalvarez commented on controllers/clients.js
> +    const filteredClients = clients.filter((client) => client.id !== req.params.id);
@amacazzaga we need to re-assign the filtered clients to the original client's array here

2021-11-09 17:17 UTC, damianalvarez approved these changes

2021-11-09 17:17 UTC, merged