MS-51: profiles-api-rest
damianalvarez/BaSD-MindSet pull request #54
Opened 2021-11-13 21:12 UTC by ValentinaCollareta

* Add new model
* Add endpoints + controllers using GET, POST, PUT & DELETE
* Import Postman collection

2021-11-13 21:57 UTC, BaltazarCortina requested changes

2021-11-13 21:57 UTC, BaltazarCortina commented on src/controllers/profiles.js
>    }
@ValentinaCollareta this is already being validated in validations/profiles.js, it doesn't need to be validated again here

2021-11-13 21:57 UTC, BaltazarCortina commented on src/routes/profiles.js
> +router.post("/", validations.validate, validations.required, profiles.create);
@ValentinaCollareta shouldn't we check that both parameters are sent (.required) before checking that they meet the other restrictions (.validate)?

2021-11-13 22:42 UTC, BaltazarCortina requested changes

2021-11-13 22:42 UTC, BaltazarCortina commented on src/validations/profiles.js
> +    }
@ValentinaCollareta we're missing a `next();` after this line

2021-11-14 14:12 UTC, nicolasblasco commented on src/models/profiles.js
> +    required: true,
@ValentinaCollareta we should add the type unique so the name of the profile can't be repeated. You define it like this --> unique: true

2021-11-14 23:24 UTC, nicolasblasco commented on src/controllers/profiles.js
>    return res.status(201).json(newProfile);
@ValentinaCollareta we should also return an error response. We could use the same promise that was used in getAll & getById function.

2021-11-15 13:15 UTC, nicolasblasco commented on src/controllers/profiles.js
> +      return res.status(200).json(newProfile);
@ValentinaCollareta we should send a 201 HTTP status request code

2021-11-15 13:18 UTC, BaltazarCortina approved these changes

2021-11-15 13:57 UTC, merged