MS-49: Sessions - API Rest
damianalvarez/BaSD-MindSet pull request #57
Opened 2021-11-15 04:17 UTC by luisnannini

Add controller, model, route, validations and collection

2021-11-15 04:21 UTC, luisnannini commented
I didnt touch "package-lock.json" :( how can I fix that..

2021-11-15 13:08 UTC, nicolasblasco commented on src/controllers/sessions.js
> +  res.status(201).json(newSession);
@luisnannini we should use a callback or a proomise to also send an error response. We could use the same promise we use in getAll.

2021-11-15 14:50 UTC, nicolasblasco commented on src/controllers/sessions.js
> +      return res.status(400).json(err);
@luisnannini we should change this HTTP response status code to 404: Not Found. We could do the same for getById, getByIdPsychologist and getByIdCandidate.

2021-11-15 14:53 UTC, nicolasblasco commented on src/controllers/sessions.js
> +      return res.status(400).json(err);
@luisnannini we should change this HTTP response status code to 404: Not Found.

2021-11-15 14:53 UTC, nicolasblasco commented on src/controllers/sessions.js
> +      return res.status(400).json(err);
@luisnannini we should change this HTTP response status code to 404: Not Found.

2021-11-15 14:54 UTC, nicolasblasco commented on src/controllers/sessions.js
> +      return res.status(400).json(err);
@luisnannini we should change this HTTP response status code to 404: Not Found.

2021-11-15 14:54 UTC, nicolasblasco commented on src/controllers/sessions.js
> +      return res.status(400).json(err);
@luisnannini we should change this HTTP response status code to 404: Not Found.

2021-11-15 14:55 UTC, nicolasblasco commented on src/controllers/sessions.js
> +      return res.status(400).json(err);
@luisnannini we should change this HTTP response status code to 404: Not Found.

2021-11-15 14:55 UTC, nicolasblasco commented on src/controllers/sessions.js
> +      return res.status(400).json(err);
@luisnannini we should change this HTTP response status code to 404: Not Found.

2021-11-15 23:32 UTC, JamirMansilla approved these changes
🚗

2021-11-16 01:48 UTC, damianalvarez requested changes

2021-11-16 01:48 UTC, damianalvarez commented on src/validations/sessions.js
> +  //const dateTime = req.body.dateTime;
@luisnannini I think that to make this work we'll need to use 

```
const dateTime = new Date(req.body.dateTime);
```

2021-11-16 15:43 UTC, luisnannini commented
Fix package-lock.json
Add date validation
Merge and fix conflicts

2021-11-16 16:22 UTC, damianalvarez approved these changes

2021-11-16 16:22 UTC, merged