Work in progress ... feature/MS 48/admin api rest
damianalvarez/BaSD-MindSet pull request #58
Opened 2021-11-15 13:50 UTC by amacazzaga

Work in progress!.
To do : - validations on update
            - postman collection

2021-11-15 14:38 UTC, nicolasblasco commented on src/models/admins.js
> +    maxlength: 20,
@amacazzaga we should write this property type in camelCase --> maxLength

2021-11-15 18:56 UTC, nicolasblasco commented on src/controllers/admins.js
> +      return res.status(400).json(err);
@amacazzaga we should change this HTTP response status code to 404: Not Found.

2021-11-15 18:56 UTC, nicolasblasco commented on src/controllers/admins.js
> +      return res.status(400).json(err);
@amacazzaga we should change this HTTP response status code to 404: Not Found.

2021-11-15 18:56 UTC, nicolasblasco commented on src/controllers/admins.js
> +      return res.status(400).json(err);
@amacazzaga we should change this HTTP response status code to 404: Not Found.

2021-11-15 19:02 UTC, nicolasblasco commented on src/models/admins.js
> +    required: true,
@amacazzaga we should add the unique type to this property so the username can't be repeated. Like this --> unique: true

2021-11-15 19:02 UTC, nicolasblasco commented on src/models/admins.js
> +    required: true,
@amacazzaga we should add the unique type to this property so the email can't be repeated. Like this --> unique: true

2021-11-15 23:33 UTC, JamirMansilla requested changes
Agus resolve the conflicts and thats it 🛩️

2021-11-16 01:46 UTC, damianalvarez reviewed
@amacazzaga don't forget to use the correct format in the PR title and the commits

2021-11-17 12:24 UTC, damianalvarez approved these changes

2021-11-17 12:25 UTC, nicolasblasco approved these changes

2021-11-17 12:28 UTC, merged